#ifndef TPF_ECS_CONFIG_H
#define TPF_ECS_CONFIG_H

#define TPF_ECS_NAME_SIZE 128
#define TPF_ECS_MAX_COMPONENTS 64
#define TPF_ECS_MAX_ENTITIES (SDL_MAX_UINT64 - 2)
#define TPF_ECS_PREALLOCATED_ENTITIES 1024
#define TPF_ECS_ALIVE_TAG "ALIVE"

#endif /* TPF_ECS_CONFIG_H */
